accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name= "accounts"
urlpatterns = [
    path("profile/", views.DisplayProfile.as_view(), name="display-profile"),
    path("link_deezer/", views.GetDeezerOAuthCode.as_view()),
    path("login/", LoginView.as_view(template_name="accounts/login.html"))
]

api/urls.py
from django.urls import path

from .views.accounts import ProfileAPI
from .views.musicdata import *
from .views.history import *
from .views.stats import *

app_name= "api"
urlpatterns = [
    path("profile", ProfileAPI.as_view()),
    path("artist/<int:id>", ArtistAPI.as_view()),
    path("releasegroup/<int:id>", ReleaseGroupAPI.as_view()),
    path("recording/<int:id>", RecordingAPI.as_view()),
    path("track/<int:id>", TrackAPI.as_view()),
    path("history", HistoryAPI.as_view()),
    path("stats", StatsAPI.as_view()),
]

history/urls.py
from django.urls import path

from . import views


app_name = "history"
urlpatterns = [
    path("overview/", views.HistoryOverview.as_view(), name="overview"),
    path("stats/", views.Statistics.as_view(), name="statistics"),
]

muzhistory/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path
from history.views import HistoryOverview
from frontend.views import app


urlpatterns = [
    #path("", HistoryOverview.as_view(), name="overview"),
    path("admin_fgcrel/", admin.site.urls),
    path("tools_nqztht/", include("tools.urls", namespace="tools")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("oldhistory/", include("history.urls", namespace="history")),
    path("api/", include("api.urls", namespace="api")),
    re_path('^(.*)$', app, name="app"),
]

history/models.py
import datetime as dt

from django.conf import settings
from django.db import models
from django.utils import timezone as tz


from deezerdata.models.deezer_objects import *
from deezerdata.models.deezer_account import *
from platform_apis.models import DeezerApiError
from tools.models import log_exceptions


class HistoryEntry(models.Model):
    """
    An entry in a profile's listening history, generally corresponding
    to the listening of a track.
    """

    class SpecialHistoryEntryChoices(models.TextChoices):
        """
        Choices for the different types of HistoryEntry in case of a
        non-track related HistoryEntry (such as retrieval errors, etc.)
        """

        LISTENING = "listening", "Track listening"  # Regular
        DEEZER_ERROR = "err_deezer", "Deezer error"
        DEEZER_ELLIPSIS = "ellipsis_deezer", "History Ellipsis (Deezer)"

    version = models.IntegerField(default=settings.MH_VERSION)
    profile = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    deezer_account = models.ForeignKey(
        "deezerdata.DeezerAccount",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    entry_type = models.CharField(
        max_length=100,
        choices=SpecialHistoryEntryChoices.choices,
        default=SpecialHistoryEntryChoices.LISTENING,
    )
    track = models.ForeignKey(
        "musicdata.Track", null=True, blank=True, on_delete=models.PROTECT
    )
    timestamp = models.PositiveIntegerField(null=True, blank=True)
    # Consistent with timestamp if it is not null.
    listening_datetime = models.DateTimeField()

    @classmethod
    @log_exceptions
    def new_deezer_track_entry(cls, entry_json, profile, deezer_account):
        """
        Creates, if not existing, a new HistoryEntry corresponding to
        the provided json data from the Deezer API.
        """
        ignored = False  #  Default value
        entry_text = str(entry_json)
        entry_listening_datetime = tz.make_aware(
            dt.datetime.fromtimestamp(entry_json["timestamp"]),
            tz.get_current_timezone(),
        )
        track_id = entry_json["id"]
        existing_entries_with_this_datetime = cls.objects.filter(
            profile=profile,
            deezer_account=deezer_account,
            listening_datetime=entry_listening_datetime,
            # timestamp=entry_json["timestamp"],
            track__deezertrack__dz_id=track_id,
        )
        #if len(existing_entries_with_this_datetime) == 0:
        if entry_listening_datetime > deezer_account.last_history_request:
            db_entry = HistoryEntry(
                profile=profile,
                deezer_account=deezer_account,
                timestamp=entry_json["timestamp"],
                listening_datetime=entry_listening_datetime,
            )
            try:
                if track_id > 0:  # Deezer track.
                    track = DeezerTrack.get_or_retrieve(track_id)[0]

                else:  # User's mp3:
                    track = DeezerMp3.get_or_retrieve(
                        track_id, deezer_account
                    )[0]
                db_entry.track = track

            except DeezerApiError as e:
                db_entry.entry_type = (
                    cls.SpecialHistoryEntryChoices.DEEZER_ERROR
                )

            db_entry.save()  # Do not save before, as a corrupted entry could
            # be stored in case of an unexpected exception.
        else:
            ignored = True
            print("Skipped")

        return ignored, entry_listening_datetime

api/views/history.py
from django.conf import settings
from django.shortcuts import redirect, render

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions


from history.models import HistoryEntry
from accounts.models import Profile
from api.serializers.history import HistoryEntrySerializer
from api.serializers.accounts import ProfileSerializer


class HistoryAPI(APIView):
    """
    View to get a profile history entries.

    This view only accessible to logged users.
    """

    authentication_classes = [authentication.SessionAuthentication]
    permission_classes = []

    def get(self, request):
        if request.user.is_authenticated:
            profile = request.user.profile
        else:
            profile = Profile.objects.filter(showcase_profile=True)[0]
        entries = HistoryEntry.objects.filter(profile=profile).order_by(
            "-listening_datetime"
        )[:100]

        serializer_entries = HistoryEntrySerializer(entries, many=True)
        serializer_profile = ProfileSerializer(profile)
        response = {
            "data": serializer_entries.data,
            "profile": serializer_profile.data,
        }

        return Response(response)

history/views.py
import datetime as dt

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Sum, Count
from django.db.models.query import EmptyQuerySet
from django.shortcuts import redirect, render
from django.utils import timezone as tz
from django.views import View

from accounts.models import Profile
from history.models import HistoryEntry
from musicdata.models import Track, Artist, Recording
from deezerdata.models.deezer_objects import DeezerTrack


class HistoryOverview(LoginRequiredMixin, View):
    """
    Displays the listening history of the logged user.
    """
    def get(self, request):
        profile = request.user.profile
        try:
            last_history_request = (
                profile.platformaccount_set.all()
                .order_by("-last_history_request")[0]
                .last_history_request
            )
        except IndexError:
            pass

        empty_track = DeezerTrack.objects.create(dz_id=0)

        current_crush = profile.get_current_crush()

        DEFAULT_ALBUM_COVER_URL = settings.DEFAULT_ALBUM_COVER_URL
        entries = (
            HistoryEntry.objects.select_related(
                "track",
                "track__deezertrack__release",
                "track__deezertrack__release__release_group",
                "track__recording",
            )
            # .annotate(contrib='track__recording__recordingcontribution_set')
            .filter(profile=profile).order_by("-listening_datetime")
        )

        paginator = Paginator(
            entries, 70, orphans=50, allow_empty_first_page=True
        )
        total_listening_duration = entries.aggregate(
            Sum("track__deezertrack__duration")
        )
        if not total_listening_duration["track__deezertrack__duration__sum"]:
            total_listening_duration_seconds = 0
        else:
            total_listening_duration_seconds = total_listening_duration[
                "track__deezertrack__duration__sum"
            ]
            date_first_entry = entries.earliest(
                "listening_datetime"
            ).listening_datetime
        total_listening_duration_hours = (
            total_listening_duration_seconds // 3600
        )
        total_listening_timedelta = dt.timedelta(
            seconds=total_listening_duration_seconds
        )

        page_number = request.GET.get("page", default=1)
        try:
            page = paginator.page(page_number)
        except EmptyPage:  # We check that the requested page exists.
            # If not, the last page is displayed.
            page = paginator.page(paginator.num_pages)
        
        num_pages = paginator.num_pages
        num_pages_m1 = num_pages - 1

        # Remember that the entries are displayed in reverse chronological
        # order.
        # This variables are needed to display the beginning and end dates of
        # the current page.
        if paginator.count > 0:
            last_entry = page.object_list[0]
            entry_count_current_page = len(page.object_list)
            first_entry = page.object_list[entry_count_current_page - 1]

        response = render(request, "history/history_overview.html", locals())
        return response


class Statistics(View):
    """
    Statistics regarding the complete history.
    """
    def rank_elements(self, queryset):
        """
        Sorts elements and assign a rank to each, taking care of
        ex aequos.
        """
        rank, count, previous, result = 0, 0, None, {}
        for elt in queryset:
            count += 1
            if elt.entry_count != previous:
                rank += count
                previous = elt.entry_count
                count = 0
            elt.rank = rank

        return queryset


    def get(self, request):
        DEFAULT_ALBUM_COVER_URL = settings.DEFAULT_ALBUM_COVER_URL
        if request.user.is_authenticated:
            profile = request.user.profile
        else:
            profile = Profile.objects.filter(showcase_profile=True)[0]

        entries = HistoryEntry.objects.filter(profile=profile)
        if not entries:
            empty_history = True
            return render(request, "history/statistics.html", locals())
        else:
            empty_history = False
        now = tz.now()

        # All time
        artists_all_time = self.rank_elements(
            Artist.objects.filter(
                recording__track__historyentry__profile=profile,
                recording__track__historyentry__entry_type="listening",
            )
            .annotate(entry_count=Count("recording__track__historyentry"))
            .order_by("-entry_count", "name")[:9]
        )

        tracks_all_time = self.rank_elements(
            Recording.objects.filter(
                track__historyentry__profile=profile,
                track__historyentry__entry_type="listening",
            )
            .annotate(entry_count=Count("track__historyentry"))
            .order_by("-entry_count", "title")[:20]
        )

        # This year
        artists_this_year = self.rank_elements(
            Artist.objects.filter(
                recording__track__historyentry__profile=profile,
                recording__track__historyentry__entry_type="listening",
                recording__track__historyentry__listening_datetime__year=tz.now().year,
            )
            .annotate(entry_count=Count("recording__track__historyentry"))
            .order_by("-entry_count", "name")[:6]
        )

        tracks_this_year = self.rank_elements(
            Recording.objects.filter(
                track__historyentry__profile=profile,
                track__historyentry__entry_type="listening",
                track__historyentry__listening_datetime__year=tz.now().year,
            )
            .annotate(entry_count=Count("track__historyentry"))
            .order_by("-entry_count", "track")[:16]
        )


        # Last 30 days
        artists_30_days = self.rank_elements(
            Artist.objects.filter(
                recording__track__historyentry__profile=profile,
                recording__track__historyentry__entry_type="listening",
                recording__track__historyentry__listening_datetime__gte=(
                    now - dt.timedelta(days=30)
                ),
            )
            .annotate(entry_count=Count("recording__track__historyentry"))
            .order_by("-entry_count", "name")[:6]
        )

        tracks_30_days = self.rank_elements(
            Recording.objects.filter(
                track__historyentry__profile=profile,
                track__historyentry__entry_type="listening",
                track__historyentry__listening_datetime__gte=(
                    now - dt.timedelta(days=30)
                ),
            )
            .annotate(entry_count=Count("track__historyentry"))
            .order_by("-entry_count", "track")[:8]
        )

        # Last 7 days
        artists_last_7days = self.rank_elements(
            Artist.objects.filter(
                recording__track__historyentry__profile=profile,
                recording__track__historyentry__entry_type="listening",
                recording__track__historyentry__listening_datetime__gte=(
                    now - dt.timedelta(days=7)
                ),
            )
            .annotate(entry_count=Count("recording__track__historyentry"))
            .order_by("-entry_count", "name")[:3]
        )

        tracks_last_7days = self.rank_elements(
            Recording.objects.filter(
                track__historyentry__profile=profile,
                track__historyentry__entry_type="listening",
                track__historyentry__listening_datetime__gte=(
                    now - dt.timedelta(days=7)
                ),
            )
            .annotate(entry_count=Count("track__historyentry"))
            .order_by("-entry_count", "track")[:6]
        )

        stats_sections = [
            {
                "title": "Les 7 derniers jours",
                "objects": {
                    "artists": artists_last_7days,
                    "tracks": tracks_last_7days,
                },
            },
            {
                "title": "Les 30 derniers jours",
                "objects": {
                    "artists": artists_30_days,
                    "tracks": tracks_30_days,
                },
            },
            {
                "title": "Cette année",
                "objects": {
                    "artists": artists_this_year,
                    "tracks": tracks_this_year,
                },
            },
            {
                "title": "Tout l'historique",
                "objects": {
                    "artists": artists_all_time,
                    "tracks": tracks_all_time,
                },
            },
        ]

        return render(request, "history/statistics.html", locals())

history/templates/history/history_overview.html
{% extends 'base.html' %}
{% load static humanize music_elements pagination_links %}

{% block title %}
Historique de {{ profile.user.username }} - MuzHistory
{% endblock %}

{% block static %}
  <link rel="stylesheet" href="{% static 'history/css/common.css'%}" />
  <link rel="stylesheet" 
      href="{% static 'history/css/pagination_links.css' %}" />
    <link rel="stylesheet" href="{% static 'history/css/player.css'%}" />
  <link rel="stylesheet" href="{% static 'history/css/overview.css'%}" />
{% endblock %}

{% block page %}
<header>
  <div class="inner_header">
    <div class="heading_and_links">
      <h1>Historique de {{ profile.user.username }}</h1>
      <div class="links">
        <a href="{% url 'history:statistics' %}" title="Statistiques">
          {% include "history/svg/icon_stats.svg" %}
        </a>
        <a href="{% url 'accounts:display-profile' %}" title="Profil">
          {% include "history/svg/icon_profile.svg" %}
        </a>
      </div>
    </div>
    <div class="history_infos">
      {% if entries %}
        <p class="history_info" title="Nombre total d'écoutes">
          {% include "history/svg/icon_number.svg" %}
          <span>
            {{ paginator.count }} écoutes
          </span>
        </p>
        <p class="history_info" title="Durée d'écoute totale">
          {% include "history/svg/icon_time.svg" %}
          <span>
            {{ total_listening_duration_hours }} heures
          </span>
        </p>
        <p class="history_info" title="Dernière mise à jour">
          {% include "history/svg/icon_clock.svg" %}
          <span>
            {{ last_history_request|naturalday:"\l\e j F Y" }}
            à {{ last_history_request|time }}
          </span>
        </p>
      {% else %}
        <p class="empty_history_message">Votre historique d'écoute est vide.</p>
      {% endif %}
    </div>
    {% if current_crush %}
      <aside class="current_crush">
          {% if current_crush.deezer_track %}
            {% track current_crush.deezer_track "Votre titre du moment" "" "" True %}
          {% endif %}
      </aside>
    {% endif %}
  </div>
</header>
<section class="entries_wrapper">
  {% if entries %}
    {% page_links paginator page_number 'history:overview' %}
    <ul class='entries'>
      {% for entry in page %}
        {% if entry.entry_type == 'ellipsis_deezer' %}
          <li>Oups... Il y a des écoutes perdues.</li>
        {% elif entry.entry_type == 'listening' and  entry.deezer_account %}
          {% with date=entry.listening_datetime|naturalday:"\L\e j F Y" time=entry.listening_datetime|time %} 
            {% track entry.track date|add:" à "|add:time "history/svg/icon_clock.svg" "Date d'écoute" False %}
          {% endwith %}
        {% endif %}
      {% endfor %}
    </ul>

    {% page_links paginator page_number 'history:overview' %}
  {% endif %}
</section>

{% include 'history/player.html' %}
{% endblock %}

{% block scripts %}
<script src="{% static 'history/js/player.js' %}"></script>
{% endblock %}

history/templates/history/pagination_links.html
<div class="pagination_links">
  <p>
    {% for num in page_numbers %}
      {% if num == 0 %}
        <span class="page_number page_number_ellipsis">...</span>
      {% elif num == current %}
        <span class="page_number" title="Page actuelle">{{ num }}</span>
      {% else %}
        <a class="page_number" title="Aller à la page {{ num }}"
            href="{% url view_name %}{{ suffix }}{{ num }}"
        >{{ num }}</a>
      {% endif %}
    {% endfor %}
  </p>
</div>

history/templates/history/player.html
{% load static music_elements %}
<section class="player">
  {% track empty_track "" "" "" %}
  <div class="player_time_infos">
    <div class="progress_container"></div>
    <div>
      <p class="player_label">30 secondes d'extrait</p>
      <p class="player_time">
        <span id="player_current_time">00:30</span> / 
        <span id="player_total_time">5:19</span>
      </p>
    </div>
  </div>
  <audio class="player_audio" src="" data-currently-playing-id=""
      data-begin-time="">
  </audio> 
</section>
<script src="{% static 'history/js/vibrant.min.js' %}"></script>
<script src="{% static 'history/js/progressbar.min.js' %}"></script>
<script src="{% static 'history/js/tinycolor.js' %}"></script>

history/templates/history/statistics.html
<!-- -*- mode: html; indent-tabs-mode: nil; tab-width: 2 -*- -->

{% extends 'base.html' %}
{% load static humanize music_elements %}

{% block title %}Statistiques{% endblock %}

{% block static %}
  <link rel="stylesheet" href="{% static 'history/css/common.css'%}" />
  <link rel="stylesheet" href="{% static 'history/css/statistics.css'%}" />
{% endblock %}

{% block page %}
<h1>Statistiques</h1>
{% if request.user.is_authenticated %}
  <a href="/history">Historique</a>
{% else %}
<a href="/history?showcase=1">Historique</a>
{% endif %}
<a href="{% url 'accounts:display-profile' %}">Profil</a>
{% if empty_history %}
<p>Votre historique d'écoute est vide.</p>
{% else %}

  {% for section in stats_sections %}
  <h2>{{ section.title }}</h2>
  <div class="stat_section">
    <div class="stat_subsection subsection_artists">
      <h3>Artistes les plus écoutés</h3>
      <ol>
        {% for artist in section.objects.artists %}
        <li>
          <div class="rank">
            <p>#{{ artist.rank }}</p>
          </div>
          <div class="artist_image">
            {% if artist.image_url_deezer_small %}
              <img src="{{ artist.image_url_deezer_medium }}"
                alt="{{ artist.name }}" />
            {% endif %}
          </div>
          <div class="artist_metadata">
            <p class="artist_name" title="{{ artist.name }}">
              {{ artist.name }}
            </p>
            <p class="listenings_count">
              {{ artist.entry_count }} écoute{{ artist.entry_count|pluralize }}
            </p>
          </div>
        </li>
        {% empty %}
        <p>Vous n'avez rien écouté durant cette période.</p>
        {% endfor %}
      </ol>
    </div>

    <div class="stat_subsection subsection_tracks">
      <h3>Morceaux les plus écoutés</h3>
      <ol>
        {% for recording in section.objects.tracks %}
        <li>
          <div class="rank">
            <p>#{{ recording.rank }}</p>
          </div>
          {% stats_recording recording %}
        </li>
        {% empty %}
        <p>Vous n'avez rien écouté.</p>
        {% endfor %}
      </ol>
    </div>
  </div>

  {% endfor %}
{% endif %}
{% endblock %}

{% block scripts %}
<script>
  function playaudio(id) {
      var allaudios = document.querySelectorAll('audio');
      var audio = document.getElementById(id);
      if (audio.paused) {
          for (var i = 0; i < allaudios.length; i++) {
              allaudios[i].pause();
          }
          audio.play();
      } else {
          audio.pause();
      }
  }
</script>
{% endblock %}

history/templates/history/track_snippet.html
<div class="track" id="track_{{ track.id }}" 
  {% if track.deezertrack %}
    data-duration="{{ track.deezertrack.duration }}"
    data-audio-src="{{ track.deezertrack.preview }}"
  {% endif %}
>
  {% if track.deezertrack %}
    <div class='album_cover' 
      {% if track.deezertrack.preview %}
        onclick="play({{ track.deezertrack.id }});"
      {% endif %}
    >
      <img crossorigin=""
      {% if track.deezertrack.deezermp3 %}
          src="{{ DEFAULT_ALBUM_COVER_URL }}"
          alt="Generic album cover" 
          title="Pas d'extrait disponible" 
      {% else %}
        {% if track.deezertrack.preview %}
            class="play_extract"
        {% endif %}
        {% if track.deezertrack.release.cover_medium %}
            src="{{ track.deezertrack.release.cover_medium }}"
        {% else %}
            src="{{ DEFAULT_ALBUM_COVER_URL }}"
        {% endif %}
          alt="
          Album cover: 
          {{ track.deezertrack.release.release_group.title }}
          " 
        {% if track.deezertrack.preview %}
            title="Écouter un extrait" 
        {% else %}
            title="Pas d'extrait disponible"
        {% endif %}
      {% endif %}
      />
    </div>

    <div class='track_metadata'>
      <p class='track_title' 
          title="{{ track.deezertrack.title_short }} {{ track.deezertrack.title_version }}"
      >
        {{ track.deezertrack.title_short }}
        <span class="track_title_version">
          {{ track.deezertrack.title_version}}
        </span>
      </p>

      <p class='artists'>
        {% if track.deezertrack %}
          {% if track.deezertrack.deezermp3 %}
            {{ track.deezertrack.deezermp3.artist_name }}
          {% else %}
            {% for contrib in track.recording.recordingcontribution_set.all %}
              <span class='
                  artist_name artist_name_role_{{ contrib.role }}
              '>
                {{ contrib.artist.name }}{% if not forloop.last %}, 
                {% endif %}
              </span>
            {% endfor %}
          {% endif %}
        {% endif %}
      </p>

      {% if not as_recording %}
        <p class="album_name">
          {% if track.deezertrack %}
            {% if track.deezertrack.deezermp3 %}
              {% if track.deezertrack.deezermp3.album_name %}
                <span class="album_hard_text">Album </span>
                {{ track.deezertrack.deezermp3.album_name }}
              {% endif %}
            {% else %}
              {% if  track.deezertrack.release.release_group.title %}
                {{ track.deezertrack.release.release_group.title }}
              {% endif %}
            {% endif %}
          {% endif %}
        </p>
      {% endif %}
      <div class='additional_info' title="{{ label }}">
        {% if icon %}{% include icon %}{% endif %}
        <p>{{ additional_info }}</p>
      </div>
    </div>
  {% endif %}
</div>