api/urls.py
from django.urls import path

from .views.accounts import ProfileAPI
from .views.musicdata import *
from .views.history import *
from .views.stats import *

app_name= "api"
urlpatterns = [
    path("profile", ProfileAPI.as_view()),
    path("artist/<int:id>", ArtistAPI.as_view()),
    path("releasegroup/<int:id>", ReleaseGroupAPI.as_view()),
    path("recording/<int:id>", RecordingAPI.as_view()),
    path("track/<int:id>", TrackAPI.as_view()),
    path("history", HistoryAPI.as_view()),
    path("stats", StatsAPI.as_view()),
]

muzhistory/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path
from history.views import HistoryOverview
from frontend.views import app


urlpatterns = [
    #path("", HistoryOverview.as_view(), name="overview"),
    path("admin_fgcrel/", admin.site.urls),
    path("tools_nqztht/", include("tools.urls", namespace="tools")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("oldhistory/", include("history.urls", namespace="history")),
    path("api/", include("api.urls", namespace="api")),
    re_path('^(.*)$', app, name="app"),
]

tools/urls.py
from django.urls import path

from . import views

app_name="tools"
urlpatterns = [
    path("exceptionlog/<int:id>", views.ExceptionLogDisplay.as_view(), name="log_display"),
    path("exceptionlogslist", views.ExceptionLogList.as_view(), name="log_list"),
]

tools/models.py
import traceback
import sys

from django.db import models
from django.utils import timezone as tz


class ExceptionLog(models.Model):
    exception_name = models.CharField(max_length=100)
    exception_module = models.CharField(max_length=1000)
    exception_value = models.CharField(max_length=1000)
    function_name = models.CharField(max_length=1000)
    traceback = models.TextField()
    occured_on = models.DateTimeField()


def log_exceptions(fn_ififoqu):
    """
    Executes the decorated function and if an exception occurs,
    stores it in the database with its traceback.
    """
    # The weird names are to unequivocally detect frames related to 
    # this decorator in the traceback.
    def wrapped_izfgzi(*args, **kwargs):
        try:
            return fn_ififoqu(*args, **kwargs)
        except Exception as e:
            now = tz.now()
            e_type, e_val, e_traceback = sys.exc_info()
            traceback_text = "".join(
                traceback.format_exception(e_type, e_val, e_traceback)
            )
            entry = ExceptionLog.objects.create(
                exception_name=e_type.__name__,
                exception_module=e_type.__module__,
                exception_value=str(e_val),
                function_name=str(fn_ififoqu).split(' ')[1],
                traceback=traceback_text,
                occured_on=now
            )
            entry.save()
            raise

    return wrapped_izfgzi

tools/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404
from django.views import View

from .models import ExceptionLog


class ExceptionLogList(View, LoginRequiredMixin):
    """
    View to list exceptions that have been logged with their
    tracebacks.
    """

    def get(self, request):
        if not request.user.is_superuser:
            raise PermissionDenied
        else:
            logs = ExceptionLog.objects.all().order_by("-occured_on")
            paginator = Paginator(
                logs, 100, orphans=50, allow_empty_first_page=True
            )
            page_no = request.GET.get("page", default=1)

            try:
                page = paginator.page(page_no)
            except EmptyPage:  # We check that the requested page exists.
                # If not, the last page is displayed.
                page = paginator.page(paginator.num_pages)

            # Remember that the entries are displayed in reverse chronological order.
            # This variables are needed to display the beginning and end dates of the
            # current page.
            if logs.count() > 0:
                last_log = page.object_list[0]
                num_log_this_page = len(page.object_list)
                first_log = page.object_list[num_log_this_page - 1]

            return render(request, "tools/exception_log_list.html", locals())


class ExceptionLogDisplay(View, LoginRequiredMixin):
    """
    View to display an exception that has been logged with its
    traceback.
    """

    def get(self, request, id):
        if not request.user.is_superuser:
            raise PermissionDenied
        else:
            log = get_object_or_404(ExceptionLog, id=id)
            traceback_list = []
            for i, line in enumerate(log.traceback.split("\n")):
                if "wrapped_izfgzi" in line or "fn_ififoqu" in line:
                    line_type = "logging"
                elif line[:9] == "Traceback":
                    line_type = "begin_tb"
                elif line[:6] == "  File":
                    line_type = "file"
                    if not "muzhistory" in line:
                        line_type = "file_dependency"
                elif line[:15] == "During handling":
                    line_type = "embedded"
                elif line[:9] == "The above":
                    line_type = "chaining"
                elif line[:4] == "    ":
                    line_type = "line"
                elif line == "":
                    line_type = "empty"
                else:
                    line_type = "exception"

                if i > 0:
                    if traceback_list[-1][0] == "file_dependency":
                        line_type = "line_dependency"

                """ line_list = []
                while len(line) > 140:
                    line_list.append(line[:140])
                    line = line[140:]
                line_list.append(line)
                line = '\n'.join(line_list) """
                traceback_list.append((line_type, line))

            return render(
                request, "tools/exception_log_display.html", locals()
            )

tools/templates/tools/exception_log_display.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'tools/style.css' %}" />
{% endblock %}

{% block title %}Error log{% endblock %}

{% block section %}

<h1>
    {{ log.exception_name }}
    <span class="exc_module">
        from <strong>{{ log.exception_module }}</strong>
    </span>
</h1>
<p class="exc_infos">
    Occured on {{ log.occured_on }} in {{ log.function_name }}
</p>

<pre class="traceback">
{% for line in traceback_list %}
<span class="tb_line tb_line_{{ line.0 }}">{{ line.1 }}</span>{% empty %}
    No traceback.
{% endfor %}
</pre>


{% endblock %}

tools/templates/tools/exception_log_list.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'tools/style.css' %}" />
{% endblock %}

{% block title %}Error logs{% endblock %}

{% block section %}

<h1 class="log_list_h1">Error logs</h1>

{% if logs %}
    <a href="{% url 'tools:log_list' %}">First page</a>
    {% if page.has_previous %}
        - <a href="{% url 'tools:log_list' %}?page={{ page.previous_page_number }}">
            Previous page
        </a>
    {% endif %}
    {% if page.has_next %}
        - <a href="{% url 'tools:log_list' %}?page={{ page.next_page_number }}">
            Next page
        </a>
    {% endif %}
{% endif %}
<table class="log_list">
    {% for log in page %}
    <tr class="log_row">
        <td></td>
        <td>
            <a href="{% url 'tools:log_display' log.id %}">
                {{ log.exception_name }}
            </a>
        </td>
        <td>{{ log.function_name }}</td>
        <td>{{ log.occured_on }}</td>
    </tr>
    {% empty %}
    No error logs.
    {% endfor %}
</table>



{% endblock %}