accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name= "accounts"
urlpatterns = [
    path("profile/", views.DisplayProfile.as_view(), name="display-profile"),
    path("link_deezer/", views.GetDeezerOAuthCode.as_view()),
    path("login/", LoginView.as_view(template_name="accounts/login.html"))
]

api/urls.py
from django.urls import path

from .views.accounts import ProfileAPI
from .views.musicdata import *
from .views.history import *
from .views.stats import *

app_name= "api"
urlpatterns = [
    path("profile", ProfileAPI.as_view()),
    path("artist/<int:id>", ArtistAPI.as_view()),
    path("releasegroup/<int:id>", ReleaseGroupAPI.as_view()),
    path("recording/<int:id>", RecordingAPI.as_view()),
    path("track/<int:id>", TrackAPI.as_view()),
    path("history", HistoryAPI.as_view()),
    path("stats", StatsAPI.as_view()),
]

history/urls.py
from django.urls import path

from . import views


app_name = "history"
urlpatterns = [
    path("overview/", views.HistoryOverview.as_view(), name="overview"),
    path("stats/", views.Statistics.as_view(), name="statistics"),
]

muzhistory/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path
from history.views import HistoryOverview
from frontend.views import app


urlpatterns = [
    #path("", HistoryOverview.as_view(), name="overview"),
    path("admin_fgcrel/", admin.site.urls),
    path("tools_nqztht/", include("tools.urls", namespace="tools")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("oldhistory/", include("history.urls", namespace="history")),
    path("api/", include("api.urls", namespace="api")),
    re_path('^(.*)$', app, name="app"),
]

accounts/models.py
import datetime as dt

from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.db import models
from django.db.models import Count
from django.utils import timezone as tz
from django.views.decorators.debug import sensitive_variables

import requests
from musicdata.models import Recording
from deezerdata.models.deezer_account import DeezerAccount
from platform_apis.models import (
    DeezerApiError,
    DeezerOAuthError,
    DeezerRefusedAccessError,
    Market,
)
from history.models import HistoryEntry


class Profile(models.Model):
    """
    Extension of the User model.
    """

    version = models.IntegerField(default=settings.MH_VERSION)
    showcase_profile = models.BooleanField(
        default=False
    )  # Whether the profile is used to showcase the app to anonymous users.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    track_location = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    @sensitive_variables("code", "params", "")
    def get_deezer_access_token(self, code):
        """
        Retrieves the user's access token from Deezer after authentication.
        """
        url = settings.DEEZER_ACCESS_TOKEN_URL
        params = {
            "app_id": settings.DEEZER_API_APP_ID,
            "secret": settings.DEEZER_API_SECRET_KEY,
            "code": code,
            "output": "json",
        }
        response = requests.get(url, params=params)

        response.raise_for_status()

        if response.text == "wrong code":
            raise DeezerOAuthError(response.text)
        else:
            response_data = response.json()

            if "access_token" in response_data:
                return response_data["access_token"]
            elif "error_reason" in response_data:
                if response_data["error_reason"] == "user_denied":
                    raise DeezerRefusedAccessError()
                else:
                    raise DeezerOAuthError(response_data["error_reason"])
            else:
                raise DeezerOAuthError("Unknown error.")

    @sensitive_variables("params_deezer_user", "access_token")
    def add_deezer_account(self, access_token):
        # We retrieve the Deezer user id to check if it is already
        # in the database.
        url_deezer_user = settings.DEEZER_API_USER_URL
        params_deezer_user = {"access_token": access_token}
        response_deezer_user = requests.get(
            url_deezer_user, params=params_deezer_user
        )
        r_data_deezer_user = response_deezer_user.json()

        try:
            error_type = r_data_deezer_user["error"]["type"]
            message = r_data_deezer_user["error"]["message"]
            code = r_data_deezer_user["error"]["code"]
            raise DeezerApiError(error_type, message, code)
        except KeyError:
            pass  # No API-related error occured.

        deezer_user_id = r_data_deezer_user["id"]

        deezer_account, created = DeezerAccount.objects.get_or_create(
            user_id=deezer_user_id,
        )

        if created:
            deezer_account.profile = self
        else:
            if (
                deezer_account.profile != self
                and deezer_account.profile != None
            ):
                raise ValueError(
                    "This Deezer account is already linked to another profile."
                )

        deezer_account.access_token = access_token
        deezer_account.status = DeezerAccount.StatusChoices.ACTIVE
        deezer_account.update()
        deezer_account.save()

    def get_current_crush(self):
        """
        Get the current crush of the user:
        the recording most listened to recently.
        """
        try:
            crush = (
                Recording.objects.filter(
                    track__historyentry__profile=self,
                    track__historyentry__entry_type="listening",
                    track__historyentry__listening_datetime__gte=(
                        tz.now() - dt.timedelta(days=14)
                    ),
                )
                .annotate(entry_count=Count("track__historyentry"))
                .order_by("-entry_count", "track")[0]
            )
        except IndexError:
            crush = HistoryEntry.objects.filter(profile=self).order_by(
                "-listening_datetime"
            )[0].track.recording

        return crush

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.views import View
from django.views.decorators.debug import sensitive_variables

from requests.exceptions import RequestException

from platform_apis.models import DeezerOAuthError
from deezerdata.models.deezer_account import DeezerAccount

from .models import Profile

class DisplayProfile(LoginRequiredMixin, View):
    """
    Displays the profile of the current user.
    """
    def get(self, request):
        profile = request.user.profile
        platform_accounts = profile.platformaccount_set.all()
        deezer_accounts = []
        for account in platform_accounts:
            try:
                deezer_accounts.append(account.deezeraccount)
            except AttributeError:  # This account is not a DeezerAccount
                pass

        deezer_link_account_url = settings.DEEZER_OAUTH_URL.format(
            settings.DEEZER_API_APP_ID, settings.DEEZER_AUTH_REDIRECT_URI
        )
        return render(request, "accounts/display_profile.html", locals())


class GetDeezerOAuthCode(View, LoginRequiredMixin):
    """
    View linked to the url to which the user is redirected after
    authorizing acces to his account on Deezer.
    """
    @sensitive_variables('access_token', 'code')
    def get(self, request):
        profile = request.user.profile
        try:
            if "code" in request.GET:
                code = request.GET["code"]
                access_token = profile.get_deezer_access_token(code)
                try:
                    profile.add_deezer_account(access_token)
                    messages.success(
                        request,
                        "Votre compte Deezer a été lié à votre "
                        "profil MuzHistory.",
                    )
                except ValueError:
                    messages.error(
                        request,
                        "Ce compte Deezer est déjà lié à un autre profile MuzHistory.",
                    )
            elif "error_reason" in request.GET:
                if request.GET["error_reason"] == "user_denied":
                    messages.error(
                        request,
                        "Vous avez refusé l'accès à votre "
                        "compte Deezer. Celui-ci n'a pas été lié à "
                        "MuzHistory.",
                    )
                else:
                    raise DeezerOAuthError(request.GET["error_reason"])
            else:
                raise DeezerOAuthError("Unknown error.")

        except (RequestException, DeezerOAuthError) as error:
            messages.error(
                request,
                "Nous avons rencontré un problème lors "
                "de la connexion à Deezer. Votre compte Deezer n'a pas "
                "pu être lié.",
            )

        return redirect("accounts:display-profile")

api/views/accounts.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect, render

from requests.exceptions import RequestException
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions


from platform_apis.models import DeezerOAuthError
from deezerdata.models.deezer_account import DeezerAccount

from accounts.models import Profile
from api.serializers.accounts import ProfileSerializer



class ProfileAPI(APIView):
    """
    View to get information about the logged user.

    Only authenticated users can access this view.
    """
    authentication_classes = [authentication.SessionAuthentication]
    permission_classes = []

    def get(self, request):
        if request.user.is_authenticated:
            profile = Profile.objects.get(user=request.user)
        else:
            profile = Profile.objects.filter(showcase_profile=True)[0]
        serializer = ProfileSerializer(profile)
        return Response(serializer.data)

accounts/templates/accounts/display_profile.html
{% extends 'base.html' %}

{% block page %}

  <h1>{{ profile.user.username }}</h1>
  
  <a href="{% url 'history:overview' %}">Historique d'écoute</a>

  <p>
    {% if profile.track_location %}
      We are tracking your location.
    {% endif %}
  </p>
  
  <ul>
    <h2>Linked accounts</h2>
    {% for account in deezer_accounts %}
      <li>{{ account.name }} (Deezer)</li>
    {% endfor %}
    <a href="{{ deezer_link_account_url }}">Link Deezer account</a>
  </ul>
  
  <p>
    <a href="{% url 'logout' %}">Logout</a>
    <a href="{% url 'password_change' %}">Change password</a>
  </p>
  
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'accounts/login.css' %}" />
{% endblock %}

{% block page %}
<div id="background">
  <div class="background_layer" id="bglayer1">
    <video src="{% static 'accounts/battery.mp4' %}" autoplay loop></video>
  </div>
  <div class="background_layer" id="bglayer2">
    <div class="colorblock" id="colorblock0"></div>
    <div class="colorblock" id="colorblock1"></div>
    <div class="colorblock" id="colorblock2"></div>
    <div class="colorblock" id="colorblock3"></div>
  </div>
  <div class="background_layer" id="bglayer3">
    <img src="https://cdns-images.dzcdn.net/images/cover/f521259784968d8d031110d287beed00/250x250-000000-80-0-0.jpg" data-infos="Madisen Ward and The Mama Bear  //  Dreams  //  Dreams"
      title="" id="cover_1" alt="album cover: Madisen Ward and The Mama Bear: Dreams" />
    <img src="https://e-cdns-images.dzcdn.net/images/cover/b8894bf272cc703027d6c2d6bc0205e2/250x250-000000-80-0-0.jpg" data-infos="Pomplamoose  //  Everybody Wants to Rule The World  //  Best of 2019"
      title="" id="cover_2" alt="album cover: Pomplamoose: Best of 2019" />
    <img src="https://cdns-images.dzcdn.net/images/cover/549d889629afc71d698f4274173d5496/250x250-000000-80-0-0.jpg" data-infos="The Airborne Toxic Event  //  Come On Out  //  Hollywood Park"
      title="" id="cover_3" alt="album cover: The Airborne Toxic Event: Hollywood Park" />
    <img src="https://e-cdns-images.dzcdn.net/images/cover/69b7dbf04ac2f1b429d2ec35a11b74ff/500x500-000000-80-0-0.jpg" data-infos="Pomplamoose  //  Instant Crush  //  Instant Crush"
      title="" id="cover_4" alt="album cover: Pomplamoose: Instant Crush" />
    <img src="https://cdns-images.dzcdn.net/images/cover/5bfd635c3bf252c6c0d3e3e4b8f53794/250x250-000000-80-0-0.jpg" data-infos="Phoenix  //  Lisztomania  //  Wolfgang Amadeus Phoenix"
      title="" id="cover_5" alt="album cover: Phoenix: Wolfgang Amadeus Phoenix" />
    <img src="https://cdns-images.deezer.com/images/cover/f47c0aa413d2f3fcf571f249f265ff1e/500x500-000000-80-0-0.jpg" data-infos="CAKE  //  Sinking Ship  //  Sinking Ship"
      title="" id="cover_6" alt="album cover: CAKE: Sinking Ship" />
    <img src="https://cdns-images.dzcdn.net/images/cover/ff84ff9cc326dcb829caca09b3da8561/250x250-000000-80-0-0.jpg" data-infos="The Osmonds  //  Down By The Lazy River  //  Very Best of The Osmonds"
      title="" id="cover_7" alt="album cover: The Osmonds: Very Best of The OSmonds" />
    <img src="https://e-cdns-images.dzcdn.net/images/cover/9be1aa05ac33f70a83dfc7cc530fa327/250x250-000000-80-0-0.jpg" data-infos="The Killers  //  Somebody Told Me  //  Hot Fuss"
      title="" id="cover_8" alt="album cover: The Killers: Hot Fuss" />
    <img src="https://cdns-images.dzcdn.net/images/cover/b298094528702627877720d0be4448b5/250x250-000000-80-0-0.jpg" data-infos="Daft Punk  //  Give Life Back To Music  //  Random Access Memories"
      title="" id="cover_9" alt="album cover: Daft Punk: Random Access Memories" />
    <img src="https://cdns-images.dzcdn.net/images/cover/a38ef87aa2917be1fe62866357f8ade1/250x250-000000-80-0-0.jpg" data-infos="The Weeknd  //  Blinding Lights  //  Blinding Lights"
      title="" id="cover_10" alt="album cover: The Weeknd: Blinding Lights" />
    <img src="https://e-cdns-images.dzcdn.net/images/cover/4a2360324af313f73b56fd1f7faaac88/250x250-000000-80-0-0.jpg" data-infos="Angèle  //  Flou  //  BROL"
      title="" id="cover_11" alt="album cover: Angèle: BROL" />


    <audio id="audio_cover_1" src="https://cdns-preview-3.dzcdn.net/stream/c-3756e63893017f05bb580876c049b3ac-4.mp3"
      preload="auto">
    </audio>
    <audio id="audio_cover_2" src="https://cdns-preview-5.dzcdn.net/stream/c-5c375750bba3cfb333bdce218151f8b1-3.mp3"
      preload="auto">
    </audio>
    <audio id="audio_cover_3" src="https://cdns-preview-7.dzcdn.net/stream/c-79a4f779d296204d674a37c8eb002978-5.mp3"
      preload="auto">
    </audio>
    <audio id="audio_cover_4" src="https://cdns-preview-5.dzcdn.net/stream/c-507b0b7ddfdb6d1a7df4d5fc8ec6c1b1-4.mp3"
      preload="auto">
    </audio>
    <audio id="audio_cover_5" src="https://cdns-preview-9.dzcdn.net/stream/c-9aa7c2d5711a7b042a24efbd96606d53-4.mp3"
      preload="auto">
    </audio>
    <audio id="audio_cover_6" src="https://cdns-preview-1.dzcdn.net/stream/c-18be437e098067da7284684b2a32f6e3-3.mp3"
      preload="auto">
    </audio>
    <audio id="audio_cover_7" src="https://cdns-preview-b.dzcdn.net/stream/c-b5069a3ba4bea504d9e9f8b59dfb8b2d-9.mp3"
      preload="auto">
    </audio>
    <audio id="audio_cover_8" src="https://cdns-preview-4.dzcdn.net/stream/c-4dc96d99edd87a3bfe2bbd8c4c8c67a9-6.mp3"
      preload="auto">
    </audio>
    <audio id="audio_cover_9" src="https://cdns-preview-f.dzcdn.net/stream/c-f91f04f9a14b6589f4493458cc951f2a-9.mp3"
      preload="auto">
    </audio>
    <audio id="audio_cover_10" src="https://cdns-preview-9.dzcdn.net/stream/c-92e1e84e8071d6ab417a236dc95ab0a9-4.mp3"
      preload="auto">
    </audio>
    <audio id="audio_cover_11" src="https://cdns-preview-a.dzcdn.net/stream/c-a3b3b7ed0b11d698ceab1c83446f9759-4.mp3"
      preload="auto">
    </audio>
  </div>
  <div class="background_layer" id="bglayer4">
    <img src="{% static 'accounts/people_playing_music.png' %}" alt="People playing music" />
    <img src="{% static 'accounts/human_playing_music.png' %}" alt="Man playing music" />
  </div>
</div>

<div id="foreground">
  <h1>Muzhist<ion-icon name="time-outline"></ion-icon>ry</h1>

  <div id="login_and_links">
    <div id="bg_login_and_links"></div>
    <div id="inner_login_and_links">
      <form method="post">
        {% csrf_token %}

        <p>Login</p>

        <div id="form_inner">
          {{ form.non_field_error }}

          {{ form.username.errors }}
          <label for="{{ form.username.id_for_label }}">Username</label>
          {{ form.username }}

          {{ form.password.errors }}
          <label for="{{ form.password.id_for_label }}">Password</label>
          {{ form.password }}

          <button type="submit">Login</button>
        </div>
      </form>
      <div class="showcase_links">
        <p>Or try the demo</p>
        <a href="{% url 'app' '' %}?showcase=1">
          <img src="{% static 'accounts/music-player.svg' %}" alt="Test the demo" />
        </a>
        <br />
        <a class="showcase_link" href="{% url 'app' '' %}?showcase=1">
          Try the demo
        </a>
      </div>
    </div>
  </div>

  <p class="footer_text">Matthias Roussel, 2020</p>

</div>

<p id="playing_track_infos">Title</p>

<script>
  var canPlayExtracts = false;

  function anyClick(e) {
    canPlayExtracts = true;
    document.removeEventListener("click", anyClick);
  }

  function playaudio(e) {
    var id = "audio_" + e.target.id;
    var audio = document.getElementById(id);
    
    var infos_p = document.querySelector("#playing_track_infos");
    if (canPlayExtracts) {
      fadeIn(audio, 500, 0.2);
      infos_p.innerHTML = e.target.dataset.infos;
    } else {
      infos_p.innerHTML = "Click on the page to play the extracts"
    }
    infos_p.style.opacity = 1;
  }

  function pauseaudio(e) {
    var id = "audio_" + e.target.id;
    var audio = document.getElementById(id);
    fadeOut(audio, 500);

    var infos_p = document.querySelector("#playing_track_infos");
    infos_p.style.opacity = 0;
  }

  function registerEvents() {
    var covers = document.querySelectorAll("#bglayer3 img");
    for (var i = 0; i < covers.length; i++) {
      covers[i].addEventListener("mouseover", function (e) { playaudio(e); });
      covers[i].addEventListener("mouseout", function (e) { pauseaudio(e); });
    }
    document.addEventListener("click", function(e) {anyClick(e);});
  }

  registerEvents();
</script>
<script src="{% static 'accounts/fade.js' %}"></script>
<script type="module" src="https://unpkg.com/ionicons@5.2.3/dist/ionicons/ionicons.esm.js"></script>
{% endblock %}